spring:
  application:
   name: myconfig-client
 
server:
   port: 8899
eureka:
 instance:
   hostname: localhost
 client:
   serviceUrl:
     defaultZone: http://${eureka.instance.hostname}:8061/eureka/
     
foo: test01
  


